apiRules:
- exclude:
    uidRegex: ^i5.Toolkit.MixedReality.Examples.*
    type: Namespace
- exclude:
    uidRegex: ^i5.Toolkit.MixedReality.Tests.*
    type: Namespace
- exclude:
    uidRegex: ^i5.Toolkit.Core.*
    type: Namespace
- exclude:
    uidRegex: ^InternalTools
    type: Namespace
- include:
    uidRegex: ^i5.*
    type: Namespace
- exclude:
    uidRegex: ^Global
    type: Namespace
- exclude:
    uidRegex: .*
    type: Namespace